### ISSUE TITLE
Ceiling Torch mod not behaving compatibly

### ISSUE THREAD

**Issue by OPStellar** [noriokun4649/TorchBowMod#13]
When I fire a TorchArrow at the ceiling, it doesn't place a torch but the arrow stick instead.

**Comment by noriokun4649** [comment]
Your posted issues lack crucial information. Please review your submissions. As you may be aware, Mods are subject to change with each version.

The version of my Mod is not specified, nor is the version of the targeted Mod. Furthermore, even the Modloader are not mentioned. In this state, I cannot take any action.

**Comment by noriokun4649** [comment]
No response, close.
