### ISSUE TITLE
korean language file

### ISSUE THREAD

**Issue by MilkissWhite** [noriokun4649/TorchBowMod#4]
small translation. edited from en-us

[ko_kr.zip](https://github.com/noriokun4649/TorchBowMod/files/4271088/ko_kr.zip)

when I named this json file "ko_KR.json", it's not working(game shows me english).
so I fixed it's name to "ko_kr.json"

---
韓国語の言語ファイルです。
ほかのファイルたちと同様にファイル名の後ろを大文字(ko_KR)にしたら作動しなかったので、小文字(ko_kr)にしました。

**Comment by noriokun4649** [comment]
Thank you. Added now.
