### ISSUE TITLE
Item animation on Forge 1.16.X

### ISSUE THREAD

**Issue by Gonzales555** [noriokun4649/TorchBowMod#6]
Hello, i was looking for an idea to realize the item animation on my bow item for 1.16.X. So i get your great mod. I saw you have the same problem. I have the solution for you that i found in the Source. All you need is to register the Properties
on the ClientSetupEvent, but see below.
Have fun and Greetings from Germany

public static void doClientStuff(FMLClientSetupEvent event) {
	
	ItemModelsProperties.func_239418_a_(ModItems.EXAMPLE_BOW, new ResourceLocation(References.MODID, "pulling"),
			(stack, world, entity) ->{
				if (entity == null) {
					return 0.0F;
				} else {
					return entity != null && entity.isHandActive() && entity.getActiveItemStack() == stack ? 1.0F : 0.0F;
				}
			});
	
	ItemModelsProperties.func_239418_a_(ModItems.EXAMPLE_BOW, new ResourceLocation(References.MODID, "pull"), 
			(stack, world, entity) ->{
          if (entity == null) {
             return 0.0F;
          } else {
             return entity.getActiveItemStack() != stack ? 0.0F : (float)(stack.getUseDuration() - entity.getItemInUseCount()) / 20.0F;
          }
       });
}

**Comment by noriokun4649** [comment]
I'm so glad to see that my problems have been solved.
Thank you so much from Japan.
