### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by Laifsyn** [noriokun4649/TorchBowMod#9]
Is the 1.18v stable for 1.18.2?

**Comment by noriokun4649** [comment]
Is this question about the Forge version?
The answer is no. 1.18.2 has not been checked and probably will not work.

**Comment by BigAl607** [comment]
Yeah, each time I try to load a modpack after adding this mod, I get this error and have no idea how to fix it:

TorchBowMod (torchbowmod) has failed to load correctly
java.lang.ExceptionInInitializerError: null

**Comment by noriokun4649** [comment]
fix it.
